language: go

go:
- 1.8

matrix:
  include:
    - os: linux

sudo: required

script:
     - cd service && make 
     - cd ..
     - git clone https://github.com/opencontainers/runc runc
     - cd runc && git checkout 992a5be178a62e026f4069f443c6164912adbf09 && make
     - sudo make install

