language: go

go:
- 1.8.3

matrix:
  include:
    - os: linux
 
sudo: required

script:
     - export CURR_DIR=$PWD
     - cd service && make 
     - cd $GOPATH/src/github.com  
     - mkdir opencontainers && cd opencontainers
     - git clone https://github.com/opencontainers/runc runc
     - cd runc && git checkout 992a5be178a62e026f4069f443c6164912adbf09 
     - make BUILDTAGS=`` 
     - sudo cp ./runc /bin/runc
     - find . | grep runc
     - /bin/runc -version
     - pwd
     - cd $CURR_DIR
     - pwd && ls 
     

