language: go

go:
- 1.8.3

matrix:
  include:
    - os: linux
 
sudo: required

script:
     - export CURR_DIR=$PWD
     - cd service && make 
     - cd $GOPATH/src/github.com  
     - mkdir opencontainers && cd opencontainers
     - git clone https://github.com/opencontainers/runc runc
     - cd runc && git checkout 992a5be178a62e026f4069f443c6164912adbf09 
     - make BUILDTAGS=`` 
     - sudo cp ./runc /bin/runc
     - find . | grep runc
     - /bin/runc -version
     - pwd
     - cd $CURR_DIR
     - pwd && ls
     - echo "install Ginkgo and Gomega"
     - go get github.com/onsi/ginkgo/ginkgo
     - go get github.com/onsi/gomega
     - echo "calling setup_test_env"
     - script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")"; pwd -P)
     - cd $script_dir
     - echo "Generate busybox rootfs directory for runC tests"
     - rootfs=runtime/runc/testbundle/rootfs
     - mkdir -p $rootfs
     - sudo mkdir -p /var/run/gcsrunc
     - sudo docker export $(sudo docker create busybox) | tar -C $rootfs -xvf - > /dev/null
     - echo "Start running unittests"
     - cd $GOPATH/src/github.com/Microsoft/opengcs/service/gcs
     - ginkgo -r -race

