language: go

go:
- 1.8.3

matrix:
  include:
    - os: linux
      addons:
         apt:
           packages:
             - gcc
  
sudo: required

script:
     - cd service && make 
     - cd ../../.. && pwd 
     - sudo apt-get install pkg-config
     - sudo apt-get install libseccomp-dev
     - sudo apt-get install seccomp*
     - go env
     - mkdir opencontainers && cd opencontainers
     - git clone https://github.com/opencontainers/runc runc
     - cd runc && git checkout 992a5be178a62e026f4069f443c6164912adbf09 
     - ls -l
     - make
     - sudo make install
     - find . | grep runc

