language: go

go:
- 1.8

matrix:
  include:
    - os: linux

sudo: required

script:
     - cd service && make 
      - cd ..
      - git clone https://github.com/opencontainers/runc
      - cd runc && make && sudo make install

